### ISSUE TITLE
Show properties of related models in list

### ISSUE THREAD

**Issue by joernroeder** [BRACKETS-by-TRIAD/admin-listing#1]
Hey,
i'm currently researching a admin ui for laravel and really like your approach! Adding fields, playing with bootstrap and vue works pretty well but i'm currently struggling with showing properties of related models in the list. I didn't find any info in the docs, can you give me some hints?

__Edit:__

I digged a bit deeper and figured out how to load the relationship but was wondering why it got lost on the way. 

```php
$listing = AdminListing::create(Author::class)
    ->modifyQuery(function ($query) {
        return $query->with('book');
    });

// relation attached! everything is fine
dd($listing->get()->first()->toArray());
```

I found the line https://github.com/BRACKETS-by-TRIAD/admin-listing/blob/master/src/AdminListing.php#L315 where the columns are passed into the paginator.

`dd` prints an empty relation `'book' => null` in the line behind and data comes back as soon as you replace `$this->materializeColumnNames($columns),` with the paginate default [`['*']`](https://laravel.com/api/5.5/Illuminate/Database/Query/Builder.html#method_paginate) or by using it as the `$columns` parameter of `processRequestAndGet`.

```php
private function buildPaginationAndGetResult($columns) {
    if ($this->hasPagination) {
        $result = $this->query->paginate($this->perPage, $this->materializeColumnNames($columns), $this->pageColumnName, $this->currentPage);
        dd($result->first()->toArray());
    }
}
```

It seems as the selection of columns (via `get` or `select`) removes the relation ship added via  `with`.

```php
dd(Autor::with('book')->first()->toArray()); // works
dd(Autor::select(['title'])->with('book')->first()->toArray()); // not
```

**Comment by palypster** [comment]
Hi Jorn, we'll have a look and let you know.

**Comment by palypster** [comment]
So we guess Author has many Books. We also guess that originally you were using `processRequestAndGet` approach and used `with()` to eager load the relations.

`with` is a special method that actually does not build anything to the query. It just eager loads with another separate query after the original query was executed. With by default loads `*` in this new query, but you can of course specify the columns you would like to retrieve using `addSelect` (but for your scenario you don't even need specify this). **In order eager loading to work, both keys (foreign key and a primary key) must be included in the appropriate query (so it can be matched)**:
https://laravel.com/docs/5.5/eloquent-relationships#eager-loading

I guess (once you provide the original code and the models we can verify), that you were missing the `id` column in the `$columns` parameter in `processRequestAndGet`. You last example confirms that (you are selecting only title, id is missing so no book can be attached to the author).

Please let us know, it that helped.
